name: "Bundlewatch Github Action"

on:
  pull_request:
    types: [synchronize, opened]
  push:
    branches:
    - master

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Build
      run: |
        npm ci
        npm run build
    - uses: jackyef/bundlewatch-gh-action@master
      with:
        bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
