name: "Bundlewatch Github Action"

on:
  pull_request:
    types: [synchronize, opened]
  push:
    branches:
    - master

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Bundlewatch (PR)
      if: github.event_name == 'pull_request'
      run: npx bundlewatch
      env:
        CI_REPO_OWNER: ${{ github.repository_owner }}
        CI_REPO_NAME: ${{ github.event.repository.name }}
        CI_COMMIT_SHA: ${{ github.sha }}
        CI_BRANCH: ${{ github.head_href }}
        BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
    - name: Bundlewatch (PUSH)
      if: github.event_name != 'pull_request'
      run: npx bundlewatch
      env:
        CI_REPO_OWNER: ${{ github.repository_owner }}
        CI_REPO_NAME: ${{ github.event.repository.name }}
        CI_COMMIT_SHA: ${{ github.sha }}
        CI_BRANCH: ${{ github.ref#refs/heads/ }}
        BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
