name: bundlewatch

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install gulp
      run: npm install --global gulp
    - name: Build
      run: |
        npm install
        gulp build
    - name: Bundlewatch Github Action
      uses: jackyef/bundlewatch-gh-action@0.0.5
